export const ADMIN_CHECKER_REQUEST = "ADMIN_CHECKER_REQUEST"
export const ADMIN_CHECKER_SUCCESS = "ADMIN_CHECKER_SUCCESS"
export const ADMIN_CHECKER_FAIL = "ADMIN_CHECKER_FAIL"



export const ADMIN_USER_LIST_REQUEST = "ADMIN_USER_LIST_REQUEST"
export const ADMIN_USER_LIST_SUCCESS = "ADMIN_USER_LIST_SUCCESS"
export const ADMIN_USER_LIST_FAIL = "ADMIN_USER_LIST_FAIL"