export const GET_Y_REQUEST = "GET_Y_REQUEST";
export const GET_Y_SUCCESS = "GET_Y_SUCCESS";
export const GET_Y_FAIL = "GET_Y_FAIL";



export const POST_Y_REQUEST = "POST_Y_REQUEST";
export const POST_Y_SUCCESS = "POST_Y_SUCCESS";
export const POST_Y_FAIL = "POST_Y_FAIL";

export const GET_DETAIL_Y_REQUEST = "GET_DETAIL_Y_REQUEST";
export const GET_DETAIL_Y_SUCCESS = "GET_DETAIL_Y_SUCCESS";
export const GET_DETAIL_Y_FAIL = "GET_DETAIL_Y_FAIL";




export const DELETE_Y_REQUEST = "DELETE_Y_REQUEST";
export const DELETE_Y_SUCCESS = "DELETE_Y_SUCCESS";
export const DELETE_Y_FAIL = "DELETE_Y_FAIL";


export const UPDATE_Y_REQUEST = "UPDATE_Y_REQUEST";
export const UPDATE_Y_SUCCESS = "UPDATE_Y_SUCCESS";
export const UPDATE_Y_FAIL = "UPDATE_Y_FAIL";

export const LIKE_Y_REQUEST = "LIKE_Y_REQUEST";
export const LIKE_Y_SUCCESS = "LIKE_Y_SUCCESS";
export const LIKE_Y_FAIL = "LIKE_Y_FAIL";


export const GET_USER_Y_REQUEST = "GET_USER_Y_REQUEST";
export const GET_USER_Y_SUCCESS = "GET_USER_Y_SUCCESS";
export const GET_USER_Y_FAIL = "GET_USER_Y_FAIL";

export const GET_USER_Y_OTHER_REQUEST = "GET_USER_Y_OTHER_REQUEST";
export const GET_USER_Y_OTHER_SUCCESS = "GET_USER_Y_OTHER_SUCCESS";
export const GET_USER_Y_OTHER_FAIL = "GET_USER_Y_OTHER_FAIL";


export const GET_LIKE_COUNT_REQUEST = "GET_LIKE_COUNT_REQUEST";
export const GET_LIKE_COUNT_SUCCESS = "GET_LIKE_COUNT_SUCCESS";
export const GET_LIKE_COUNT_FAIL = "GET_LIKE_COUNT_FAIL";